# fly.toml app configuration file generated for bellevue-rabbitmq on 2025-06-05T23:16:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bellevue-rabbitmq'
primary_region = 'bos'

[build]
  image = 'rabbitmq:3-management'

[env]
  RABBITMQ_DEFAULT_PASS = 'guest'
  RABBITMQ_DEFAULT_USER = 'guest'

[[services]]
  protocol = 'tcp'
  internal_port = 5672

  [[services.ports]]
    port = 5672

[[services]]
  protocol = 'tcp'
  internal_port = 15672

  [[services.ports]]
    port = 15672

[[services]]
  protocol = 'tcp'
  internal_port = 61613

  [[services.ports]]
    port = 61613

[checks]
  [checks.rabbit]
    port = 5672
    type = 'tcp'
    interval = '30s'
    timeout = '10s'

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2

[experimental]
  cmd = [
    "/bin/sh",
    "-c",
    "rabbitmq-plugins enable --offline rabbitmq_stomp && rabbitmq-server"
  ]