INSERT INTO avatar (name) VALUES ('cat'), ('raptor'), ('walrus'), ('bee'), ('monkey'), ('horse');
INSERT INTO item (name, slot, starter, unlockable) VALUES
('red_cap', 'hat', true, false),
('blue_cap', 'hat', true, false),
('yellow_cap', 'hat', true, false),
('green_cap', 'hat', true, false),
('black_hat', 'hat', true, false),
('white_hat', 'hat', true, false),
('brown_hat', 'hat', true, false);

INSERT INTO forum (name, description) VALUES
('Town Hall', 'Where neighbors gather to chat about anything and everything.'),
('News Station', 'Tuning in to the latest headlines, scoops, and spirited debates.'),
('Event Space', 'Booking the next big bash or planning a quiet little get-together.'),
('Airport', 'Swapping travel tales, itineraries, and packing secrets.'),
('Culinary Center', 'Cooking up recipes, restaurant tips, and midnight snack confessions.'),
('Book Store', 'Flipping through pages, sharing bookish thoughts, and trading reads.'),
('Museum', 'Admiring the past, decoding culture, and arguing about art.'),
('Movie Theater', 'Reviewing blockbusters, indie gems, and everything in between.'),
('Television Studio', 'Bingeing shows, dodging spoilers, and rating cliffhangers.'),
('Concert Hall', 'Tapping toes, singing along, and arguing over “best album ever.”'),
('Video Game Store', 'Leveling up, sharing strategies, and debating game lore.'),
('Board Game Store', 'Rolling dice, flipping cards, and settling rules disputes.'),
('Garden', 'Swapping seeds, showing off harvests, and chatting compost.'),
('Gym', 'Breaking a sweat, chasing gains, and dodging leg day.'),
('Liquor Store', 'Pouring pints, mixing drinks, and toasting to taste.'),
('Workshop', 'Hammering, gluing, and proudly showing off slightly crooked shelves.'),
('Garage', 'Fixing engines, comparing mods, and bonding over busted bolts.'),
('Laboratory', 'Mixing ideas, testing theories, and geeking out over discoveries.'),
('Hacker Den', 'Coding, debugging, and sharing the occasional cursed regex.'),
('Court House', 'Debating laws, decoding policies, and delivering hot takes on justice.'),
('Hospital', 'Sharing health tips, wellness wins, and “should I see a doctor?” moments.'),
('Police Station', 'Talking true crime, neighborhood safety, and mystery solving.'),
('Playground', 'Swapping parenting wins, woes, and creative snack ideas.'),
('School', 'Trading tips on homework, lunchbox lore, and class projects.'),
('University', 'Studying hard, procrastinating harder, and philosophizing at 2 a.m.'),
('Temple', 'Lighting candles, asking big questions, and finding quiet moments.'),
('Train Station', 'Catching trains, complaining about delays, and sharing commute hacks.'),
('Office', 'Vent sessions, work wins, and career advice from the watercooler crowd.'),
('Park', 'Stretching legs, tossing ideas around, and enjoying the open air of random chat.'),
('Recycling Center', 'Sorting thoughts on sustainability, zero waste, and greener living.'),
('Shelter', 'Offering support, sharing resources, and being there for one another.');
