INSERT INTO ingredient (name, pescetarian, vegetarian, vegan, gluten_free, allergen) VALUES
  ('tomato', 1, 1, 1, 1, NULL),
  ('chicken', 0, 0, 0, 1, NULL),
  ('quinoa', 1, 1, 1, 1, NULL),
  ('peanut butter', 1, 1, 0, 1, 'nuts'),
  ('oats', 1, 1, 1, 1, NULL),
  ('cucumber', 1, 1, 1, 1, NULL),
  ('bell pepper', 1, 1, 1, 1, NULL),
  ('carrot', 1, 1, 1, 1, NULL),
  ('broccoli', 1, 1, 1, 1, NULL),
  ('spinach', 1, 1, 1, 1, NULL),
  ('mushroom', 1, 1, 1, 1, NULL),
  ('zucchini', 1, 1, 1, 1, NULL),
  ('potato', 1, 1, 1, 1, NULL),
  ('eggplant', 1, 1, 1, 1, NULL),
  ('onion', 1, 1, 1, 1, NULL),
  ('garlic', 1, 1, 1, 1, NULL),
  ('olive oil', 1, 1, 1, 1, NULL),
  ('basil', 1, 1, 1, 1, NULL),
  ('oregano', 1, 1, 1, 1, NULL),
  ('chickpeas', 1, 1, 1, 1, NULL),
  ('lentils', 1, 1, 1, 1, NULL),
  ('brown rice', 1, 1, 1, 1, NULL),
  ('chicken breast', 0, 0, 0, 1, NULL),
  ('ground beef', 0, 0, 0, 1, NULL),
  ('salmon', 1, 0, 0, 1, NULL),
  ('eggs', 0, 1, 0, 1, NULL),
  ('almonds', 1, 1, 1, 1, 'nuts'),
  ('peanuts', 1, 1, 1, 1, 'peanuts'),
  ('walnuts', 1, 1, 1, 1, 'nuts'),
  ('flour', 1, 1, 1, 0, 'gluten'),
  ('sugar', 1, 1, 1, 1, NULL),
  ('honey', 1, 1, 0, 1, NULL),
  ('soy sauce', 1, 1, 1, 0, 'soy'),
  ('coconut milk', 1, 1, 1, 1, NULL),
  ('yogurt', 0, 1, 0, 1, 'dairy'),
  ('cheese', 0, 1, 0, 1, 'dairy'),
  ('butter', 0, 1, 0, 1, 'dairy'),
  ('tofu', 1, 1, 1, 1, NULL),
  ('tempeh', 1, 1, 1, 1, NULL),
  ('pasta', 1, 1, 1, 0, 'gluten'),
  ('bread', 1, 1, 1, 0, 'gluten'),
  ('cabbage', 1, 1, 1, 1, NULL),
  ('cauliflower', 1, 1, 1, 1, NULL),
  ('all-purpose flour', 1, 1, 1, 0, 'gluten'),
  ('baking powder', 1, 1, 1, 1, NULL),
  ('baking soda', 1, 1, 1, 1, NULL),
  ('granulated sugar', 1, 1, 1, 1, NULL),
  ('brown sugar', 1, 1, 1, 1, NULL),
  ('powdered sugar', 1, 1, 1, 1, NULL),
  ('vanilla extract', 1, 1, 1, 1, NULL),
  ('cocoa powder', 1, 1, 1, 1, NULL),
  ('milk', 1, 1, 0, 1, 'dairy'),
  ('shortening', 1, 1, 1, 1, NULL),
  ('yeast', 1, 1, 1, 1, NULL),
  ('chocolate chips', 1, 1, 1, 1, 'dairy'),
  ('nuts', 1, 1, 1, 1, 'nuts'),
  ('cream cheese', 1, 1, 0, 1, 'dairy'),
  ('pecan meal', 1, 1, 1, 1, 'nuts'),
  ('almond flour', 1, 1, 1, 1, 'nuts'),
  ('tuna', 1, 0, 0, 1, 'fish'),
  ('shrimp', 1, 0, 0, 1, 'shellfish'),
  ('cod', 1, 0, 0, 1, 'fish'),
  ('mackerel', 1, 0, 0, 1, 'fish'),
  ('cumin', 1, 1, 1, 1, NULL),
  ('paprika', 1, 1, 1, 1, NULL),
  ('salt', 1, 1, 1, 1, NULL),
  ('pepper', 1, 1, 1, 1, NULL),
  ('cream', 1, 1, 0, 1, 'dairy'),
  ('lemon', 1, 1, 1, 1, NULL),
  ('thyme', 1, 1, 1, 1, NULL),
  ('avocado', 1, 1, 1, 1, NULL),
  ('maple syrup', 1, 1, 1, 1, NULL),
  ('celery', 1, 1, 1, 1, NULL);

INSERT INTO skill (name) VALUES
  ('place'),
  ('start'),
  ('mix'),
  ('stir'),
  ('add'),
  ('remove'),
  ('flip'),
  ('drain'),
  ('rinse'),
  ('clean'),
  ('cut'),
  ('peel'),
  ('skin'),
  ('dice'),
  ('chop'),
  ('mince'),
  ('slice'),
  ('grate'),
  ('fillet'),
  ('heat'),
  ('cook'),
  ('simmer'),
  ('fry'),
  ('sauté'),
  ('boil'),
  ('steam'),
  ('bake'),
  ('roast'),
  ('broil'),
  ('grill'),
  ('cool'),
  ('freeze'),
  ('blend');

INSERT INTO equipment (name) VALUES
  ('knife'),
  ('whisk'),
  ('grater'),
  ('spoon'),
  ('spatula'),
  ('fork'),
  ('bowl'),
  ('plate'),
  ('tray'),
  ('glass'),
  ('baking tray'),
  ('baking sheet'),
  ('cake pan'),
  ('pan'),
  ('pot'),
  ('wok'),
  ('mixer'),
  ('rice cooker'),
  ('toaster'),
  ('microwave'),
  ('toaster oven'),
  ('convection oven'),
  ('air fryer'),
  ('deep fryer'),
  ('grill'),
  ('stove'),
  ('oven'),
  ('blender');
