# fly.toml app configuration file generated for bellevue-mysql on 2025-06-05T23:13:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bellevue-mysql'
primary_region = 'bos'

[build]
  dockerfile = 'Dockerfile'

[env]
  MYSQL_DATABASE = 'bellevue_dev'
  MYSQL_ROOT_PASSWORD = 'root'
  TZ = 'America/New_York'

[[mounts]]
  source = 'mysqldata'
  destination = '/data'

[[vm]]
  cpu_kind = 'shared'
  cpus = 8
  memory = '16gb'
