# fly.toml app configuration file generated for bellevue-redis on 2025-06-05T23:15:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bellevue-redis'
primary_region = 'bos'

[build]
  image = 'redis:6'

[checks]
  [checks.redis]
    port = 6379
    type = 'tcp'
    interval = '30s'
    timeout = '10s'

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
